### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by cagatayldzz** [humhub/humhub-modules-notes#17]
http://translate.humhub.org/index.php?r=notes%2Fnote%2Fopen&id=2&sguid=1d601225-6793-4e4f-9a6b-5e4bda0d4f97
![bda142b6-0fbf-11e6-8c96-dd9819ca2f01](https://cloud.githubusercontent.com/assets/7725575/14943271/b6911b96-0fdc-11e6-9575-77ef1785b1cf.png)

**Comment by MatthiasHertel** [comment]
i have the same issue ... how to set the api key ... or where can i set the api key in the module ?
