### ISSUE TITLE
Unable to resolve the request "notes/noteconfig/index"

### ISSUE THREAD

**Issue by Tagussan** [humhub/humhub-modules-notes#3]
After I installed humhub and confirmed it works correctly, I installed etherpad-lite. When I installed etherpad-notes module, I got this error message:Unable to resolve the request "notes/noteconfig/index"
What should I do?

**Comment by Vamoss** [comment]
I did a pullRequest to solve this:
https://github.com/humhub/humhub-modules-notes/pull/5

**Comment by luke-** [comment]
Thanks - I've merged it
