### ISSUE TITLE
Setup instructions missing?

### ISSUE THREAD

**Issue by brecke** [humhub/humhub-modules-notes#7]
Hi there,

I've installed and set up etherpad locally in the same VM as the one humhub is running on but I can't get it to work. I've followed the instructions but this is what I get so far:

![screen shot 2015-01-30 at 17 25 10](https://cloud.githubusercontent.com/assets/19879/5980114/35a9e336-a8a5-11e4-80b6-45d02c1486b6.png)

I can't seem to edit the note, all I see is its empty value :-/ What am I missing here?

**Comment by brecke** [comment]
OK, I think it has to do with having humhub in https and etherpad in regular http. However, I am unable to get the SSL to work. If I try to use https in the url field, I no longer get the connection working:

```
Current Status: Could not connect to API!
```

Help?

**Comment by brecke** [comment]
Nevermind, the problem was that I was using 127.0.0.1 and it started working as soon as I changed it to the real IP. Noob.

**Comment by bigdriveca** [comment]
Where did you change this?

**Comment by brecke** [comment]
In humhub configuration page, if I remember correctly.

**Comment by ericomcolen** [comment]
Hi, I've tried everything to make it work but this module is too complicated. Can you help me please.
