### ISSUE TITLE
Konnte den Request "notes/noteconfig/index" nicht auflösen.

### ISSUE THREAD

**Issue by toearc** [humhub/humhub-modules-notes#9]
Protokollierung:
Error ... exception.CHttpException.404
exception 'CHttpException' with message 'Konnte den Request "notes/noteconfig/index" nicht auflösen.' in /var/www/humhub/protected/vendors/yii/web/CWebApplication.php:286 Stack trace: #0 /var/www/humhub/protected/vendors/yii/web/CWebApplication.php(141): CWebApplication->runController('notes/noteconfi...') #1 /var/www/humhub/protected/vendors/yii/base/CApplication.php(180): CWebApplication->processRequest() #2 /var/www/humhub/index.php(39): CApplication->run() #3 {main} REQUEST_URI=/index.php?r=notes/noteconfig/index ---

git clone, 2015-02-08, version Version: 0.10.1
noteconfig noteConfig

**Comment by luke-** [comment]
https://github.com/humhub/humhub-modules-notes/commit/32f0be4874a7a8501171f1f76b1c71d2629a7997
